### ISSUE TITLE
3.7.630.62903 Synapse has stopped ScrollFunctionLock from working

### ISSUE THREAD

**Issue by thedraken** [CodeNeedsCoffee/ScrollFunctionLock#1]
The latest version of the Razer Synapse software has stopped the ScrollFunctionLock from working, It appears Razer have locked the function keys so they can no longer be re-mapped

**Comment by thedraken** [comment]
I've noticed you have created a new tag with a potential fix in, however it does not have version of the synapse3 file, just a readme.md

**Comment by CodeNeedsCoffee** [comment]
Hey @thedraken!

Great question, unfortunately the synapse files are already compiled and Razer doesn't have a native way to get the raw data. And attempting to follow best git practices (which it's not recommended to include executable/compiled files with in the repo) I have the just the read me in the repo and then the synapse files under the release page: [Releases](https://github.com/CodeNeedsCoffee/ScrollFunctionLock/releases)

Let me know if you still have this issue!

**Comment by ariksu** [comment]
@CodeNeedsCoffee thank you for your work, but somehow latest release does not contain a .synapse3 file. Could you check, please?

**Comment by CodeNeedsCoffee** [comment]
@ariksu and @thedraken I've updated the latest release to patch the issues reported.

[Latest Release](https://github.com/CodeNeedsCoffee/ScrollFunctionLock/releases/latest)
